# Copyright (c) 2023 by Marcin Nowicki
# frozen_string_literal: true

source 'https://rubygems.org'

# Keep in sync with .ruby-version
ruby '3.1.3'

# This is a gem all dependencies loosely defined there
gemspec
